#define ISRAFILCORE_PROJECT_NAME        "IsrafilCore"
#define ISRAFILCORE_PROJECT_DESCRIPTION "LER0ever Project Israfil Core Library"

#define ISRAFILCORE_AUTHOR_ORGANIZATION "LER0ever"
#define ISRAFILCORE_AUTHOR_DOMAIN       "http://etasry.ml"
#define ISRAFILCORE_AUTHOR_MAINTAINER   "etasry@gmail.com"

#define ISRAFILCORE_VERSION_MAJOR       "0"
#define ISRAFILCORE_VERSION_MINOR       "1"
#define ISRAFILCORE_VERSION_PATCH       "2"
#define ISRAFILCORE_VERSION_REVISION    "000000000004"

#define ISRAFILCORE_VERSION             "0.1.2"
#define ISRAFILCORE_NAME_VERSION        "IsrafilCore v0.1.2 (000000000004)"
